//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleRental
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bicycle_rental2DBEntities : DbContext
    {
        public bicycle_rental2DBEntities()
            : base("name=bicycle_rental2DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bicycle> Bicycles { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Electric_bicycle> Electric_bicycle { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Regular_bicycle> Regular_bicycle { get; set; }
        public virtual DbSet<Unicycle> Unicycles { get; set; }
    }
}
