//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electric_bicycle
    {
        public int article_number { get; set; }
        public string frame_number { get; set; }
        public string battery_capacity { get; set; }
        public string battery_avg_charge_time { get; set; }
        public string battery_avg_distance { get; set; }
        public string motor_power { get; set; }
    
        public virtual Bicycle Bicycle { get; set; }
    }
}
