//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public string social_security_number { get; set; }
        public string frame_number { get; set; }
        public Nullable<System.DateTime> rent_start { get; set; }
        public Nullable<System.DateTime> rent_stop { get; set; }
        public Nullable<int> total_price { get; set; }
        public string payment_method { get; set; }
        public Nullable<System.DateTime> order_made { get; set; }
    
        public virtual Bicycle Bicycle { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
